### ISSUE TITLE
Your project not working on Device Farm

### ISSUE THREAD

**Issue by vietch2612** [awslabs/aws-device-farm-appium-tests-for-sample-app#3]
Hi,

I clone your project, build it and upload to my Device Farm, but your script not work?
Only 2 suite on report: Setup & TearDown? What happend?

**Comment by appwiz** [comment]
@vietch2612 - could you provide a console link to the run?

**Comment by vietch2612** [comment]
Ah, thank for your reply.
That is my mistake, your project and my project is worked. 

I use your script: testPackage.sh then its work, but i type mvn package -Dskiptests=true on Terminal i get unkown command message. Can you let me know?

**Comment by appwiz** [comment]
@vietch2612 - hmm, could you paste the message? I suspect maven is not in your path.
