### ISSUE TITLE
Unable to find the testng xml in the project structure 

### ISSUE THREAD

**Issue by sanojqa** [awslabs/aws-device-farm-appium-tests-for-sample-app#7]
Unable to find the testng xml in the project. I need to run my test in the specific order and where can I mention the tests?

**Comment by nikhil-dabhade** [comment]
Unfortunately, test ordering is not supported via testng.xml today. 
You could, however, achieve this by having one test which calls the other tests in the order desired.
The downside to this approach being that device farm will track that one test on a high level so any failures in the test will need to be figured out by digging in the logs.
