### ISSUE TITLE
Which test to be run first ? Where to configure this ?

### ISSUE THREAD

**Issue by adarshem** [awslabs/aws-device-farm-appium-tests-for-sample-app#8]
I am new with maven and AWS. 

As per the steps mentioned in AWS I am able to create .zip file successfully for my Junit project. Now I am not sure how or where I can configure the order of my tests. Lets say I have 5 test classes and I want to have a specific order for that,.

Kindly let me know how to proceed here ? Please do explain how AWS will take the tests and run.

Appreciate your input

Regards,
Adarsh E M

**Comment by nikhil-dabhade** [comment]
Unfortunately, there is no way to specify the order of tests to be executed. 

One way, however, would be to have one test that calls the other tests in the order that you prefer.
The downside to this approach is that the end results would show only one test and any failures will need looking at logs to figure out the failure.
